//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedHost) DeepCopyInto(out *AllowedHost) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedHost.
func (in *AllowedHost) DeepCopy() *AllowedHost {
	if in == nil {
		return nil
	}
	out := new(AllowedHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionServiceAccount) DeepCopyInto(out *UnionServiceAccount) {
	*out = *in
	if in.Allowlist != nil {
		in, out := &in.Allowlist, &out.Allowlist
		*out = make([]AllowedHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionServiceAccount.
func (in *UnionServiceAccount) DeepCopy() *UnionServiceAccount {
	if in == nil {
		return nil
	}
	out := new(UnionServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionTeamServiceAccounts) DeepCopyInto(out *UnionTeamServiceAccounts) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionTeamServiceAccounts.
func (in *UnionTeamServiceAccounts) DeepCopy() *UnionTeamServiceAccounts {
	if in == nil {
		return nil
	}
	out := new(UnionTeamServiceAccounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnionTeamServiceAccounts) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionTeamServiceAccountsList) DeepCopyInto(out *UnionTeamServiceAccountsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnionTeamServiceAccounts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionTeamServiceAccountsList.
func (in *UnionTeamServiceAccountsList) DeepCopy() *UnionTeamServiceAccountsList {
	if in == nil {
		return nil
	}
	out := new(UnionTeamServiceAccountsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnionTeamServiceAccountsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionTeamServiceAccountsSpec) DeepCopyInto(out *UnionTeamServiceAccountsSpec) {
	*out = *in
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]UnionServiceAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionTeamServiceAccountsSpec.
func (in *UnionTeamServiceAccountsSpec) DeepCopy() *UnionTeamServiceAccountsSpec {
	if in == nil {
		return nil
	}
	out := new(UnionTeamServiceAccountsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionTeamServiceAccountsStatus) DeepCopyInto(out *UnionTeamServiceAccountsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionTeamServiceAccountsStatus.
func (in *UnionTeamServiceAccountsStatus) DeepCopy() *UnionTeamServiceAccountsStatus {
	if in == nil {
		return nil
	}
	out := new(UnionTeamServiceAccountsStatus)
	in.DeepCopyInto(out)
	return out
}
