//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleAPI) DeepCopyInto(out *GoogleAPI) {
	*out = *in
	if in.ImpersonatedAccounts != nil {
		in, out := &in.ImpersonatedAccounts, &out.ImpersonatedAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleAPI.
func (in *GoogleAPI) DeepCopy() *GoogleAPI {
	if in == nil {
		return nil
	}
	out := new(GoogleAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Host) DeepCopyInto(out *Host) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Host.
func (in *Host) DeepCopy() *Host {
	if in == nil {
		return nil
	}
	out := new(Host)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionServiceAccount) DeepCopyInto(out *UnionServiceAccount) {
	*out = *in
	if in.ExternalAllowlist != nil {
		in, out := &in.ExternalAllowlist, &out.ExternalAllowlist
		*out = make([]Host, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InternalAllowlist != nil {
		in, out := &in.InternalAllowlist, &out.InternalAllowlist
		*out = make([]Host, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrivateGoogleAPIs != nil {
		in, out := &in.PrivateGoogleAPIs, &out.PrivateGoogleAPIs
		*out = make([]GoogleAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionServiceAccount.
func (in *UnionServiceAccount) DeepCopy() *UnionServiceAccount {
	if in == nil {
		return nil
	}
	out := new(UnionServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionTeamServiceAccounts) DeepCopyInto(out *UnionTeamServiceAccounts) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionTeamServiceAccounts.
func (in *UnionTeamServiceAccounts) DeepCopy() *UnionTeamServiceAccounts {
	if in == nil {
		return nil
	}
	out := new(UnionTeamServiceAccounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnionTeamServiceAccounts) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionTeamServiceAccountsList) DeepCopyInto(out *UnionTeamServiceAccountsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnionTeamServiceAccounts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionTeamServiceAccountsList.
func (in *UnionTeamServiceAccountsList) DeepCopy() *UnionTeamServiceAccountsList {
	if in == nil {
		return nil
	}
	out := new(UnionTeamServiceAccountsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnionTeamServiceAccountsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionTeamServiceAccountsSpec) DeepCopyInto(out *UnionTeamServiceAccountsSpec) {
	*out = *in
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]UnionServiceAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionTeamServiceAccountsSpec.
func (in *UnionTeamServiceAccountsSpec) DeepCopy() *UnionTeamServiceAccountsSpec {
	if in == nil {
		return nil
	}
	out := new(UnionTeamServiceAccountsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnionTeamServiceAccountsStatus) DeepCopyInto(out *UnionTeamServiceAccountsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnionTeamServiceAccountsStatus.
func (in *UnionTeamServiceAccountsStatus) DeepCopy() *UnionTeamServiceAccountsStatus {
	if in == nil {
		return nil
	}
	out := new(UnionTeamServiceAccountsStatus)
	in.DeepCopyInto(out)
	return out
}
