---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.nav.no
  resources:
  - unionteamserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.nav.no
  resources:
  - unionteamserviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - data.nav.no
  resources:
  - unionteamserviceaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.cnrm.cloud.google.com
  resources:
  - iampolicymembers
  - iamserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
