apiVersion: data.nav.no/v1alpha1
kind: UnionTeamServiceAccounts
metadata:
  labels:
    app.kubernetes.io/name: union-operator
    app.kubernetes.io/managed-by: kustomize
  name: unionteamserviceaccounts-sample
  namespace: dataplattform-staging
spec:
  project: dataplattform
  domain: development
  serviceAccounts:
    - name: dataplattform
      externalAllowlist:
        - host: nav.no
      cloudSQLInstances:
        - ip: 34.88.169.172
