apiVersion: data.nav.no/v1
kind: UnionTeamServiceAccounts
metadata:
  labels:
    app.kubernetes.io/name: union-operator
    app.kubernetes.io/managed-by: kustomize
  name: unionteamserviceaccounts-sample
  namespace: dataplattform-development
spec:
  project: dataplattform
  domain: development
  serviceAccounts:
    - name: dataplattform-tester
      externalAllowlist:
        - host: vg.no
        - host: example.com
      internalAllowlist:
        - host: a01dbfl039.adeo.no
