apiVersion: data.nav.no/v1
kind: UnionTeamServiceAccounts
metadata:
  labels:
    app.kubernetes.io/name: union-operator
    app.kubernetes.io/managed-by: kustomize
  name: unionteamserviceaccounts-sample
  namespace: dataplattform-development
spec:
  # TODO(user): Add fields here
  name: dataplattform-test
  serviceAccounts:
    - name: dataplattform
      allowlist:
        - host: github.com
          port: 443
          paths: ["navikt/*"]        
    - name: dataplattform-dvh-prod
      allowlist:
        - host: dmv04-scan.adeo.no
          port: 1521
          protocol: TCP
          paths: ["*"]
