apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/default
configMapGenerator:
- files:
  - config.yaml=config-dev.yaml
  name: manager-config
  namespace: union-operator-system
