apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/default
  - kyvernopolicy.yaml
patches:
  - path: service-account-patch.yaml
configMapGenerator:
- files:
  - config.yaml=config-prod.yaml
  name: manager-config
  namespace: union-operator-system
generatorOptions:
  disableNameSuffixHash: true
