apiVersion: v1
kind: ServiceAccount
metadata:
  name: union-operator-controller-manager
  namespace: union-operator-system
  annotations:
    iam.gke.io/gcp-service-account: union-operator@nav-data-union-restricted-prod.iam.gserviceaccount.com
